Session/2
kitamura5897/yumemi-ios-trainning pull request #2
Opened 2023-02-23 09:30 UTC by kitamura5897

## 修正内容
- ボタンをタップして天気予報を取得する
- 天気予報を画面に表示する
- [参考]
 [session/2](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/API.md)
## レビュー観点
- APIから取得した文字列で表示する画像を変えるためにif文を使っているのですが、冗長な気がしているため何か良い書き方があれば教えてください。

## レビューレベル
希望するレビューレベルを[x]のようにしてください。
- ~~Lv0: まったく見ないでAcceptする~~
-  Lv1: ぱっとみて違和感がないかチェックしてAcceptする
- ~~Lv2: 仕様レベルまで理解して、仕様通りに動くかある程度検証してAcceptする~~
- ~~LV3: 実際に環境で動作確認したうえでAcceptする~~
詳細は[こちら](https://yumemi.qiita.com/shared/items/0b1c393e24f99025608d)
## スクリーンショット

https://user-images.githubusercontent.com/101320377/220868494-44ee1b00-f43f-4673-a24c-ff472b5a3833.mp4

## 備考
* マージ先のブランチの設定が正しいか確認してください。

2023-02-23 14:21 UTC, KantaSwift requested changes

2023-02-23 14:21 UTC, KantaSwift commented on yumemi-ios-trainning/WeatherViewController.swift
> +    }()
[nits]
適切な命名に変更しよう

2023-02-23 14:21 UTC, KantaSwift commented on yumemi-ios-trainning/WeatherViewController.swift
> +        button.setTitleColor(UIColor.blue, for: .normal)
[nits]
UIColorは推論で省略できる。

2023-02-23 14:21 UTC, KantaSwift commented on yumemi-ios-trainning/WeatherViewController.swift
> +        button.setTitleColor(UIColor.blue, for: .normal)
[nits]
ditto

2023-02-23 14:21 UTC, KantaSwift commented on yumemi-ios-trainning/WeatherViewController.swift
> +    }
[imo]

```
enum Weather: String {
   case sunny
   case rainy
   case cloudy
    
    private var color: UIColor {
        switch self {
        case .sunny:
            return .red
        case .cloudy:
            return .gray
        case .rainy:
            return .blue
        }
    }
    
    var image: UIImage {
        return UIImage(named: rawValue)!.withTintColor(color)
    }
}
```
こういうのを作ってあげてこれを呼び出してあげよう!

2023-02-23 14:21 UTC, KantaSwift commented on yumemi-ios-trainning/WeatherViewController.swift
> +    private lazy var rightbutton: UIButton = {
[nits]
適切な命名にしよう

2023-02-23 14:21 UTC, KantaSwift commented on yumemi-ios-trainning/WeatherViewController.swift
> +    private lazy var leftbutton: UIButton = {
適切な命名にしよう

2023-02-25 05:42 UTC, Ryu0118 commented on yumemi-ios-trainning/WeatherViewController.swift
> +    private let imageview: UIImageView = {
変数の命名は、lower camel caseでとういつ.
`imageView`

2023-02-25 05:42 UTC, Ryu0118 commented on yumemi-ios-trainning/WeatherViewController.swift
> +         buttonStackView.widthAnchor.constraint(equalTo: totalStackView.widthAnchor)].forEach { $0.isActive = true }
前のPRのreviewと一緒

2023-02-25 05:42 UTC, Ryu0118 commented on yumemi-ios-trainning/WeatherViewController.swift
> +    }
```Swift
enum Weather: String {
   case sunny
   case rainy
   case cloudy
    
    private var color: UIColor {
        switch self {
        case .sunny:
            return .red
        case .cloudy:
            return .gray
        case .rainy:
            return .blue
        }
    }
    
    var image: UIImage? {
        return UIImage(named: rawValue)?.withTintColor(color)
    }
}
```
これでいいです

2023-02-25 05:49 UTC, KantaSwift commented on yumemi-ios-trainning/WeatherViewController.swift
> +    }
すみません。強制アンラップしてました

2023-02-25 09:08 UTC, KantaSwift reviewed
追加です
[FYI]
baseブランチを main ではなく session/1 にすると、2の方の差分のみ抽出できるのと、1がマージされたらこのPRも自動的に main に向けられるという観点からsession/1に変えましょう

2023-02-25 09:30 UTC, kitamura5897 commented on yumemi-ios-trainning/WeatherViewController.swift
> +         buttonStackView.widthAnchor.constraint(equalTo: totalStackView.widthAnchor)].forEach { $0.isActive = true }
@Ryu0118  上條がなんか言ってたけど直していいの？

2023-02-25 09:36 UTC, kitamura5897 commented
@KantaSwift  basebranchを変更した

2023-02-25 09:38 UTC, kitamura5897 commented on yumemi-ios-trainning/WeatherViewController.swift
> +        button.setTitleColor(UIColor.blue, for: .normal)
[c3c90c9](https://github.com/kitamura5897/yumemi-ios-trainning/pull/2/commits/c3c90c9118a3677387fa69e025b3e47be5ed52bb)

2023-02-25 09:38 UTC, kitamura5897 commented on yumemi-ios-trainning/WeatherViewController.swift
> +        button.setTitleColor(UIColor.blue, for: .normal)
[c3c90c9](https://github.com/kitamura5897/yumemi-ios-trainning/pull/2/commits/c3c90c9118a3677387fa69e025b3e47be5ed52bb)

2023-02-25 09:39 UTC, kitamura5897 commented on yumemi-ios-trainning/WeatherViewController.swift
> +    }
[33e2162](https://github.com/kitamura5897/yumemi-ios-trainning/pull/2/commits/33e2162102a545a3d728e861d636fd42131542ce)

2023-02-25 09:39 UTC, kitamura5897 commented on yumemi-ios-trainning/WeatherViewController.swift
> +    }()
[4f9408c](https://github.com/kitamura5897/yumemi-ios-trainning/pull/2/commits/4f9408cb1cc2857a4cfacbc44c416b75920a2ee0)

2023-02-25 09:39 UTC, kitamura5897 commented on yumemi-ios-trainning/WeatherViewController.swift
> +    private lazy var leftbutton: UIButton = {
[4cc0623](https://github.com/kitamura5897/yumemi-ios-trainning/pull/2/commits/4cc0623b4cfb8c2401017048a04b97e96ba0be35)

2023-02-25 09:40 UTC, kitamura5897 commented on yumemi-ios-trainning/WeatherViewController.swift
> +    private lazy var rightbutton: UIButton = {
[4cc0623](https://github.com/kitamura5897/yumemi-ios-trainning/pull/2/commits/4cc0623b4cfb8c2401017048a04b97e96ba0be35)

2023-02-25 10:01 UTC, KantaSwift commented
LGTMです！

2023-02-25 10:02 UTC, KantaSwift approved these changes

2023-03-07 09:24 UTC, Ryu0118 approved these changes

2023-03-07 11:09 UTC, merged